Added 40 minutes timer
AntonMaksimenkau/team4_backend pull request #101
Opened 2021-08-11 12:34 UTC by Anlord241

2021-08-11 13:46 UTC, Darina007 approved these changes

2021-08-11 14:01 UTC, AntonMaksimenkau requested changes

2021-08-11 14:01 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/TestsController.java
> +    public long getTimeLeft(@PathVariable("testId") long testId) {
don't need to have a separate endpoint for it. Just set the finishTime to a test on /start requests

2021-08-11 14:01 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestsServiceImpl.java
> +    private void setTimer(long id) {
it won't work after restarts. There can be 3 options here:
1. store the timers in DB and recover them on app start
2. find external timer for it
3. make a lazy finish

BTW: don't forget that after the time had passed, we still need to receive some frontend requests wtih the answers

2021-08-12 06:49 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestsServiceImpl.java
> +    private void setTimer(long id) {
Anyway, we have some separate tasks to finish the test. You don't need to do it here

2021-08-12 17:57 UTC, maxim12321 reviewed
Don't you think that all the work with timers can be moved from the `TestsService` to a separate service?

2021-08-12 18:10 UTC, Anlord241 commented
> Don't you think that all the work with timers can be moved from the `TestsService` to a separate service?

Yes, I do (I even did so in the beginning)
But I think it's impossible because of cycles (we need to use `TestsService`  methods in `TimerService` and vice versa)

2021-08-12 18:19 UTC, maxim12321 commented
Why we need to use `TestsService` methods in `TimerService`?
It seeems that `createTimer`, `startTimer` and `startAllTimers` methods don't depend on `TestsService` and can be easily extracted to a separate service :)

2021-08-12 18:30 UTC, Anlord241 commented
> Why do we need to use `TestsService` methods in `TimerService`?
> It seeems that `createTimer`, `startTimer` and `startAllTimers` methods don't depend on `TestsService` and can be easily extracted to a separate service :)

`startTimer` calls `finish` from `TestsService`
  and 
`startAllTimers`, `createTimer` call `startTimer`
___________________________________________________
It means, that all methods from `TimerService` call `finish` :)

2021-08-12 18:39 UTC, maxim12321 commented
Maybe you can use something like callback function?)
So, you can pass function as a parameter for `Timer` (e.g. your `TestsService::finish` or it's wrapper), that will be called after timer is out.
IDK should we do that or not))

2021-08-13 09:03 UTC, maxim12321 approved these changes

2021-08-13 10:40 UTC, AntonMaksimenkau requested changes

2021-08-13 10:40 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestsServiceImpl.java
> +        test.setFinishTime(Instant.now().plusSeconds(42 * 60));
now().plus(40l, ChronoUnit.MINUTES)?

2021-08-13 10:40 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestsServiceImpl.java
> +        test.setFinishTime(Instant.now().plusSeconds(42 * 60));
we decided to use 42 munutes for a timer. For the test it still should be 40 mins?

2021-08-13 10:40 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestsServiceImpl.java
> +        testsRepository.finish(finishDate, id);
Should we stop timer in case user finished it?

2021-08-13 20:14 UTC, AntonMaksimenkau approved these changes

2021-08-13 21:01 UTC, merged