Fix
AntonMaksimenkau/team4_backend pull request #107
Opened 2021-08-12 17:17 UTC by Darina007

2021-08-12 18:27 UTC, maxim12321 requested changes

2021-08-12 18:27 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/dto/TestDTO.java
> +    private ListeningTopicRequest contentFile;
I think that's not `request` anymore :)

2021-08-12 18:47 UTC, maxim12321 approved these changes

2021-08-13 06:07 UTC, AntonMaksimenkau approved these changes

2021-08-13 08:47 UTC, merged