Add Liquibase
AntonMaksimenkau/team4_backend pull request #2
Opened 2021-07-07 10:46 UTC by SemyonKorostik

2021-07-07 11:35 UTC, AntonMaksimenkau commented on pom.xml
> +				<version>4.4.0</version>
Let's put the liquibase version in the properties section.
https://maven.apache.org/pom.html#Properties
Plugin and dependency versions are highly coupled, so it makes sense to store it at one place

2021-07-07 11:37 UTC, AntonMaksimenkau commented on pom.xml
> +				<version>4.4.0</version>
Let's put the first liquibase script which will create the database.
You can find the sql here: https://github.com/mtalstykh-exadel/team4_docs/blob/main/architecture/backend/database-sceme/db/language-testing.sql

2021-07-08 11:12 UTC, AntonMaksimenkau requested changes

2021-07-08 11:12 UTC, AntonMaksimenkau commented on pom.xml
> -	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
please, use 4 spaces code style

2021-07-08 12:23 UTC, mpasenko commented on src/main/resources/db/changelog/db.changelog-master.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please rename file. Good practice to is when file hase name related to ticket. For instance: if you are going to create database schema your file will have name 'create-db.xml'

2021-07-08 12:23 UTC, mpasenko commented on src/main/resources/db/changelog/db.changelog-master.xml
> +    <preConditions>
I think this preCondition is redundant. You can define DBMS in properties file

2021-07-08 12:23 UTC, mpasenko commented on src/main/resources/application.properties
> +logging.level.liquibase=DEBUG
remove pls

2021-07-08 13:02 UTC, mpasenko submitted a review, later dismissed

2021-07-08 14:12 UTC, Darina007 submitted a review, later dismissed

2021-07-09 06:13 UTC, AntonMaksimenkau approved these changes

2021-07-09 06:17 UTC, AntonMaksimenkau approved these changes

2021-07-09 07:16 UTC, Darina007 approved these changes

2021-07-09 07:59 UTC, maxim12321 approved these changes

2021-07-09 08:10 UTC, merged