Crud: content files
AntonMaksimenkau/team4_backend pull request #25
Opened 2021-07-20 19:43 UTC by Anlord241

2021-07-21 06:55 UTC, AntonMaksimenkau requested changes

2021-07-21 06:55 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/exceptions/FileNotFoundException.java
> -public class NotFoundException extends RuntimeException{
What do you think about NotFoundException and its extensions: FileNotFound, QuestionNotFound etc?

2021-07-21 06:55 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/ContentFilesService.java
> +        contentFilesRepository.deleteById(id);
Why don't you like the same approach as with updateUrl?
It should return the number of affected rows as well.
Maybe you'll need to specify the method in interface

2021-07-21 06:55 UTC, AntonMaksimenkau commented on src/test/java/com/team4/testingsystem/controllers/ContentFilesControllerTest.java
> +        verify(contentFilesService).add("https://zaycev.net/", 1L);
let's get rid of pirate site links in a repository :)

2021-07-21 09:57 UTC, maxim12321 requested changes

2021-07-21 09:57 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/controllers/ContentFilesController.java
> +    private ContentFilesServiceImpl contentFilesService;
We use `@Autowired` with constructors, not directly fields.

2021-07-21 09:57 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/controllers/ContentFilesController.java
> +    private ContentFilesServiceImpl contentFilesService;
It seems that bean of type `ContentFilesService` should be injected, not the specific implementation.

2021-07-21 09:57 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/services/impl/ContentFilesServiceImpl.java
> +        contentFile.setQuestion(question);
I think it can be done using constructor with 2 params

2021-07-21 09:57 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/services/impl/LevelServiceImpl.java
> +        return levelRepository.findByName(name).orElseThrow(QuestionNotFoundException::new);
You mean `LevelNotFoundException`?)

2021-07-21 09:57 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/services/impl/ModuleServiceImpl.java
> +        return moduleRepository.findByName(name).orElseThrow(QuestionNotFoundException::new);
And here `ModuleNotFoundException` then

2021-07-21 09:57 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/services/impl/UsersServiceImpl.java
> +        return usersRepository.findById(id).orElseThrow(QuestionNotFoundException::new);
`UserNotFoundException` :)

2021-07-21 11:54 UTC, maxim12321 approved these changes

2021-07-22 08:08 UTC, AntonMaksimenkau approved these changes

2021-07-22 08:09 UTC, maxim12321 approved these changes

2021-07-22 08:09 UTC, merged