Switched jococo to pitest
AntonMaksimenkau/team4_backend pull request #29
Opened 2021-07-21 14:57 UTC by Darina007

2021-07-21 15:10 UTC, maxim12321 submitted a review, later dismissed

2021-07-21 15:13 UTC, AntonMaksimenkau requested changes
there should be a configuration, that will fail build in case mutation coverage < 60%

2021-07-21 18:22 UTC, maxim12321 approved these changes

2021-07-22 06:34 UTC, AntonMaksimenkau requested changes
Can't see how it should fail a build.
You need to add the plugin execution on a mvn verify stage (better solution) ot to add a step with it's execution to a maven.yml github action

Let's also add coverageThreshold to 70

2021-07-22 08:42 UTC, AntonMaksimenkau approved these changes

2021-07-22 08:43 UTC, maxim12321 approved these changes

2021-07-22 08:44 UTC, merged