Described all endpoints using swagger
AntonMaksimenkau/team4_backend pull request #40
Opened 2021-07-24 08:50 UTC by Anlord241

Authentication, CRUD for tests, CRUD for content files, CRUD for file answers, CRUD for questions

2021-07-26 06:34 UTC, AntonMaksimenkau requested changes
Please, add the authorization with the swagger.
Here is a good example: https://www.baeldung.com/spring-boot-swagger-jwt

2021-07-26 07:40 UTC, maxim12321 approved these changes

2021-07-27 06:02 UTC, AntonMaksimenkau approved these changes

2021-07-27 06:06 UTC, AntonMaksimenkau commented
Please, add the instruction with URL and login instruction from above to docs instead of current API info

2021-07-27 07:08 UTC, merged