Crud for options
AntonMaksimenkau/team4_backend pull request #49
Opened 2021-07-28 15:13 UTC by DzmitryNovik

2021-07-28 15:21 UTC, AntonMaksimenkau requested changes

2021-07-28 15:21 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/ChosenOptionService.java
> +    ChosenOption getById(ChosenOptionID chosenOptionID);
getByTest

2021-07-28 15:21 UTC, AntonMaksimenkau commented on src/main/resources/db/changelog/changes/schema.xml
> +            </column>
create a new changeset instead of modifying existant one

2021-07-28 15:21 UTC, AntonMaksimenkau commented on src/test/java/com/team4/testingsystem/services/impl/ChosenOptionImplTest.java
> +        Mockito.when(chosenOptionRepository.findById(chosenOptionID)).thenThrow(FileNotFoundException.class);
Definitely, it's not fileNotFound

2021-07-28 15:21 UTC, AntonMaksimenkau commented on src/test/java/com/team4/testingsystem/services/impl/ChosenOptionImplTest.java
> +        verify(chosenOptionRepository).save(any());
verify ... save (choosenOption)

2021-07-29 10:45 UTC, AntonMaksimenkau requested changes

2021-07-29 10:45 UTC, AntonMaksimenkau commented on src/test/java/com/team4/testingsystem/services/impl/ChosenOptionImplTest.java
> +        Mockito.when(chosenOptionRepository.findChosenOptionsByTest(test)).thenThrow(ChosenOptionNotFoundException.class);
Don't think repository will throw such exception

2021-07-29 10:45 UTC, AntonMaksimenkau commented on src/test/java/com/team4/testingsystem/services/impl/ChosenOptionImplTest.java
> +        ArrayList<ChosenOption> chOptions = new ArrayList<>();
let's add some options here

2021-07-29 10:45 UTC, AntonMaksimenkau commented on src/main/resources/db/changelog/changes/schema.xml
> +                                 constraintName="chosen_option_file_answer_fk"
All the changes in schema.xml should be done in a separate changeSet

2021-07-30 08:17 UTC, maxim12321 requested changes

2021-07-30 08:17 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/repositories/ChosenOptionRepository.java
> +    Iterable<ChosenOption> findChosenOptionsByTest(Test test) throws ChosenOptionNotFoundException;
How does this method throw custom exception?

2021-07-30 11:58 UTC, AntonMaksimenkau approved these changes

2021-07-30 17:39 UTC, maxim12321 approved these changes

2021-08-03 13:29 UTC, merged