test generating service
AntonMaksimenkau/team4_backend pull request #54
Opened 2021-07-29 17:56 UTC by Darina007

2021-07-30 07:13 UTC, AntonMaksimenkau requested changes
Any tests here?

2021-07-30 07:13 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/repositories/ContentFilesRepository.java
> +    List<ContentFile> getRandomFiles(String level, Pageable pageable);
why do we need a list of random files?

2021-07-30 07:13 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestGeneratingServiceImpl.java
> +    private static final Pageable COUNT_QUESTIONS_GRAMMAR = Pageable.ofSize(12);
lets move constants to property file

2021-07-30 07:13 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/repositories/ContentFilesRepository.java
> +    List<ContentFile> getRandomFiles(String level, Pageable pageable);
BTW, does the pagination works on CrudRepository extention with queries without its direct usage

2021-07-30 12:00 UTC, AntonMaksimenkau approved these changes

2021-07-30 12:00 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestGeneratingServiceImpl.java
> +    private static final Pageable COUNT_QUESTIONS_GRAMMAR = Pageable.ofSize(12);
I think, 10 questions are enough

2021-07-30 15:53 UTC, AntonMaksimenkau requested changes

2021-07-30 15:53 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestGeneratingServiceImpl.java
> +    private Integer oneElement;
One element seems to be technical value, rather the user defines constant. No need to read it from properties.

2021-07-30 15:53 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/TestGeneratingServiceImpl.java
> +    public Test generateTest(Test test) {
Generate test method that takes test from the argument seams weird

2021-08-02 08:46 UTC, AntonMaksimenkau approved these changes

2021-08-02 08:51 UTC, maxim12321 approved these changes

2021-08-02 08:59 UTC, merged