endpoint for finished tests
AntonMaksimenkau/team4_backend pull request #61
Opened 2021-08-02 16:39 UTC by Darina007

2021-08-03 06:41 UTC, AntonMaksimenkau requested changes

2021-08-03 06:41 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/enums/Status.java
> +    STARTED
Minor:  let's set the values in the status changing order

2021-08-03 06:41 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/enums/Status.java
> +    STARTED
Wait a bit with it. I think it's not a full list of statuses

2021-08-04 09:12 UTC, AntonMaksimenkau requested changes

2021-08-04 09:12 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/TestsController.java
> +        List<Test> tests = testsService.getByStatus(Status.COMPLETED);
It could be 2 statuses here. Anyway, will decided on meeting at 2 pm

2021-08-04 09:12 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/TestsController.java
> +        tests.forEach(test -> testDTOS.add(new TestDTO(test)));
List<TestDTO> testDTOS = tests.stream().map(TestDTO::new).collect(Collectors.toList())

2021-08-04 16:19 UTC, maxim12321 approved these changes

2021-08-04 16:26 UTC, AntonMaksimenkau approved these changes

2021-08-04 16:37 UTC, merged