Authentication using JWT token
AntonMaksimenkau/team4_backend pull request #7
Opened 2021-07-08 16:47 UTC by maxim12321

Add custom UserDetails, storing the information about the user (now: login, password, role).
Configure Spring Security to use JWT token for authentication.

`/login` endpoint performs authentication using user's login and password, returns generated JWT token.
Other endpoints accept only authenticated users.

Provide unit-tests for services and JWT utilities.

2021-07-08 17:07 UTC, AntonMaksimenkau requested changes
Please, have a look at the comments

2021-07-08 17:07 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/TestingSystemApplication.java
> -	public static void main(String[] args) {
Please, use a single code style within your team

2021-07-08 17:07 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/config/WebSecurityConfiguration.java
> +    @Autowired
Currently, injection in a constructor known as a best practice. Let's use it

2021-07-08 17:07 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/config/WebSecurityConfiguration.java
> +        return NoOpPasswordEncoder.getInstance();
NoopPasswordEncoder is insecure. Let's use BcryptPasswordEncoder instead

2021-07-08 17:07 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/AuthenticationController.java
> +    @GetMapping("/")
What is index page here and why do we need it?

2021-07-08 19:49 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/controllers/AuthenticationController.java
> +    @GetMapping("/")
It was used to make the first request and get CSRF token from the response
If the request fails (e.g. 403 error), will token still be attached to the responce header?

2021-07-08 19:59 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/AuthenticationController.java
> +    @GetMapping("/")
So it was used only for test purposes. Do you think we need it on a prod environment?

2021-07-08 20:01 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/controllers/AuthenticationController.java
> +    @GetMapping("/")
😳

2021-07-08 20:05 UTC, AntonMaksimenkau requested changes
Still have some issues with a code style. Please, set code style settings in your ide to default and make a refactoring

2021-07-09 06:14 UTC, AntonMaksimenkau submitted a review, later dismissed

2021-07-09 06:44 UTC, SemyonKorostik approved these changes, later dismissed

2021-07-09 07:17 UTC, Darina007 submitted a review, later dismissed

2021-07-09 08:54 UTC, AntonMaksimenkau requested changes

2021-07-09 08:54 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/entities/UserRoleEntity.java
> +    private Integer id;
Integer is too small for users.
Let's use at least Long

2021-07-09 09:08 UTC, AntonMaksimenkau approved these changes

2021-07-09 09:09 UTC, Darina007 approved these changes, later dismissed

2021-07-09 09:12 UTC, AntonMaksimenkau requested changes

2021-07-09 09:12 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/entities/UserEntity.java
> +public class UserEntity {
Do we really need Entity postifx?

2021-07-09 09:12 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/entities/UserRoleEntity.java
> +public class UserRoleEntity {
Same here

2021-07-09 09:28 UTC, maxim12321 commented on src/main/java/com/team4/testingsystem/entities/UserEntity.java
> +public class UserEntity {
Nope, not really)

2021-07-09 09:35 UTC, AntonMaksimenkau approved these changes

2021-07-09 10:05 UTC, Anlord241 approved these changes

2021-07-09 10:09 UTC, merged