controller for chosen option
AntonMaksimenkau/team4_backend pull request #77
Opened 2021-08-05 10:51 UTC by DzmitryNovik

2021-08-05 11:08 UTC, AntonMaksimenkau requested changes

2021-08-05 11:08 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/ChosenOptionController.java
> +    public Iterable<ChosenOption> getAllByTest(@RequestBody Test test) {
I think it should be testId as a parameter here. And /{testId} seams to be a good path for it

2021-08-05 11:08 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/ChosenOptionController.java
> +    }
Please, add a method to provide a list of ChoosenOptions's.
I expect to see the params as 
{ 
testId: 123,
  choosen: [{
  questionId: 3,
  answerId: 6
  },{ 
  questionId: 2,
  answerId: 7
  }, ...
  ]}

2021-08-09 15:56 UTC, AntonMaksimenkau commented on src/test/java/com/team4/testingsystem/services/impl/ChosenOptionImplTest.java
> +        chosenOptions.add(new ChosenOption());
List<ChosenOption> chosenOptions = Lists.of(new ChosenOption(), new ChosenOption(), new ChosenOption())

2021-08-09 15:56 UTC, AntonMaksimenkau approved these changes

2021-08-09 16:30 UTC, maxim12321 approved these changes

2021-08-09 17:44 UTC, merged