Update listening
AntonMaksimenkau/team4_backend pull request #89
Opened 2021-08-10 11:09 UTC by Darina007

2021-08-10 13:37 UTC, AntonMaksimenkau requested changes

2021-08-10 13:37 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/QuestionServiceImpl.java
> +        ContentFile contentFile = contentFilesRepository.findById(id)
Let's archive content file

2021-08-10 15:34 UTC, Darina007 commented on src/main/java/com/team4/testingsystem/services/impl/QuestionServiceImpl.java
> +        ContentFile contentFile = contentFilesRepository.findById(id)
don't we need to archive questions if we change the file?

2021-08-10 17:10 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/QuestionServiceImpl.java
> +        ContentFile contentFile = contentFilesRepository.findById(id)
Theoretically, yes.
In practice, the listening test is generated by a chosen content file. If a file is archived, the questions will never be found.
Alternatively, you can make a single request, that will archive all the questions by its content file. But definitely we don't need to make 10 requests for it

2021-08-10 17:20 UTC, AntonMaksimenkau requested changes

2021-08-10 17:20 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/controllers/QuestionController.java
> +    }
Please, move the logic outside from the controller

2021-08-11 06:34 UTC, AntonMaksimenkau requested changes

2021-08-11 06:34 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/ContentFilesService.java
> +    ContentFile update(MultipartFile file, Long id, List<Question> questions);
It's pretty strange that 2 of the operations have different file type

2021-08-11 06:34 UTC, AntonMaksimenkau commented on src/main/java/com/team4/testingsystem/services/impl/ContentFilesServiceImpl.java
> +            return contentFilesRepository.save(contentFile);
Is it possible, that between `archiveQuestions` and save `ContentFile` with a new one someone will generate a test with it, or open the content file to edit?
If so, I think it's inappropriate and we should deal with it. I could suggest you 2 options:
1.  make the method `@Transactional`. If the changes will be made in a single transaction, we shouldn't have any problems with it
2. Even though we are not updating the file, we can create a new `ContentFile` with the same URL data and archive the previous one.

2021-08-11 14:02 UTC, AntonMaksimenkau approved these changes

2021-08-11 14:43 UTC, maxim12321 approved these changes

2021-08-11 15:13 UTC, merged